os: linux
dist: xenial
language: cpp
sudo: enabled

env:
  - ENABLE_MPI=OFF
  - ENABLE_MPI=ON

install:
  - export ROOTDIR=`pwd`
  - sudo apt-get update
  - sudo apt-get install -y gcc gfortran cmake liblapack-dev
  - sudo apt-get install -y libopenmpi-dev openmpi-bin
  - sudo apt-get install -y libscalapack-mpi-dev
  - sudo apt-get install -y python
  - sudo apt-get install -y python-numpy python-scipy python-toml
  - sudo apt-get install -y python3
  - sudo apt-get install -y python3-numpy python3-scipy python3-toml
script:
  - cd ${ROOTDIR}
  - mkdir build
  - cd build
  - cmake -DENABLE_MPI=${ENABLE_MPI} ../
  - VERBOSE=1 make
  - ctest -VV

jobs:
  include:
    - stage: deploy docs
      if: fork = false
      install:
        - export ROOTDIR=`pwd`
        - sudo apt-get update
        - sudo apt-get install -y gcc gfortran cmake liblapack-dev
        - sudo apt-get install -y python3
        - sudo apt-get install -y python3-numpy python3-scipy python3-toml python3-sphinx
        - mkdir build
        - cd build
        - cmake -DDocument=ON -DENABLE_MPI=OFF ../
        - VERBOSE=1 make doc
        - cd ${ROOTDIR}
      script: /bin/bash -x ./.travis/deploy_docs.sh
